### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: Provider "jar" not installed

### ISSUE THREAD

**Issue by drtomforce** [NicklasWallgren/bankid-java-sdk#4]
Hej och tack för ditt arbete!

Använder Android Studio. Har fastnat i problem med vad jag tror beror på getResource() i tryUriFrom(). 

final URI caResourceUri = ResourceUtils.tryUriFrom("certificate.pem")
Så här ser min URI ut: caResourceUri : jar:file:/data/app/com.example.bluetoothfunctions-_gxA3PsSi10D4dBRV0j7PQ==/base.apk!/certificate.pem

När jag använder Paths.get(caResourceUri) får jag felmeddelande där felet verkar börja här: Caused by: java.nio.file.FileSystemNotFoundException: Provider "jar" not installed at java.nio.file.Paths.get(Paths.java:147)

Förstår jag rätt kan problemet ha att göra med konklusionen nedan som gör att detta kan fungera i test men inte "at runtime eftersom "there's no resource file at runtime" : "To conclude - URL returned by ClassLoader.getResource cannot be converted to java.io.File as a resource cannot be expressed as java.io.File. "

https://msitko.pl/blog/2019/10/19/when-your-code-fails-after-being-packaged-as-jar.html

Det verkar föreslås att man använder getResourceAsStream istället men då faller många funktioner eftersom de kräver en Path. Eller har jag missförstått något?

**Comment by NicklasWallgren** [comment]
Du har helt korrekt, jag ser till att släppa en ny version under morgondagen.

**Comment by NicklasWallgren** [comment]
Fixed in latest version.
