### ISSUE TITLE
 Problem att läsa in pkcs12Resource och caResource med ResourceUtils.tryInputStreamFrom()

### ISSUE THREAD

**Issue by drtomforce** [NicklasWallgren/bankid-java-sdk#5]
Jag hade problem att läsa in pkcs12Resource och caResource med ResourceUtils.tryInputStreamFrom()

Löstes genom att ändra till:
private static ClassLoader classLoader() {
        return ResourceUtils.class.getClassLoader();
    }

https://codeql.github.com/codeql-query-help/java/java-unsafe-get-resource/

**Comment by NicklasWallgren** [comment]
Oklart var `ResourceUtils` kommer ifrån i det här sammanhanget.

Du är välkommen att använda vilken metod du än vill för att ladda en resource, `ResourceUtils.tryInputStreamFrom` är bara ett hjälpmedel.
