### ISSUE TITLE
"PKCS12 key store mac invalid - wrong password or corrupted file" i Android Studio med senaste TLS certifikat för test: FPTestcert4_20230629.p12

### ISSUE THREAD

**Issue by drtomforce** [NicklasWallgren/bankid-java-sdk#6]
Felet uppkommer med Android Studio i SslUtils 
tryCreateKeyManager() 
clientStore.load(keystore, password.toCharArray());

Det fungerar dock med tidigare certifikat, tex FPTestcert4_20220818.p12

Sannolikt beroende på detta:

Senaste .p12 versionen fungerar inte med Android Studio Trust Manager:
https://stackoverflow.com/questions/71872900/installing-pcks12-certificate-in-android-wrong-password-bug

”Apparently Android cannot import newer pkcs12 files. I tried this on Android 12 and Android 13. This is what man openssl-pkcs12 says for -legacy:
In the legacy mode, the default algorithm for certificate encryption is RC2_CBC or 3DES_CBC depending on whether the RC2 cipher is enabled in the build. The default algorithm for private key encryption is 3DES_CBC. If the legacy option is not specified, then the legacy provider is not loaded and the default encryption algorithm for both certificates and private keys is AES_256_CBC with PBKDF2 for key derivation.”

**Comment by NicklasWallgren** [comment]
Det tidigare certifikatet hade gått ut, så jag ersatte med det senaste från BankID.

Tyvärr kan jag inte hjälpa dig felsöka det här, då det är ett Android-specifikt problem.
