### ISSUE TITLE
Didn't find class "java.net.http.HttpClient" on path: DexPathList i Android Studio

### ISSUE THREAD

**Issue by drtomforce** [NicklasWallgren/bankid-java-sdk#7]
Felet uppkommer i Android Studio Client 
Client(HttpClient.newBuilder()

Kan det bero på att java.net.http inte finns i Android Studio?

https://stackoverflow.com/questions/71344568/import-java-net-http-httprequest-import-java-net-http-httpresponse-and-import

Jag försöker att bygga om koden för att använda okhttp men är tveksam att jag har kompetensen som behövs

**Comment by NicklasWallgren** [comment]
Android har tyvärr inte stöd för `java.net.http.HttpClient`.

Öppna en ny issue om du vill att jag ska överväga att lägga till stöd för `OkHttpClient`.
